### ISSUE TITLE
Support for when dim(X)>1

### ISSUE THREAD

**Issue by SGH-188** [wesselb/gpar#4]
Dear senior,

I recently research the paper about gpar and try to run the code which you write. 
When dim(X)>1. these codes can be applied to implement?
If there are any examples or documentation how to do this, please send me in that direction (I cannot find any right now).

Best,
GHS

**Comment by wesselb** [comment]
Hey @SGH-188,

Thanks for opening an issue!

The code should already be compatible with multidimensional inputs. For example, the [Jura experiment](https://github.com/wesselb/gpar/blob/master/examples/paper/jura.py) uses two-dimensional inputs. I'm closing the issue for now, but if you encounter any issues, please feel free to reopen it or leave a comment here. :)

**Comment by SGH-188** [comment]
Dear wesselb:




Thank you so much for the prompt response! I will study in depth the proposal you sent me.


Best wishes
Yours sincerely
SGH










At 2022-05-03 15:29:23, "Wessel" ***@***.***> wrote:

Hey @SGH-188,

Thanks for opening an issue!

The code should already be compatible with multidimensional inputs. For example, the Jura experiment uses two-dimensional inputs. I'm closing the issue for now, but if you encounter any issues, please feel free to reopen it or leave a comment here. :)

**Comment by SGH-188** [comment]
Dear wesselb:


Because my data matrix is not positive-definite sometimes, when I use your code of gpar, there is a problem of 'torch.linalg_cholesky: The factorization could not be completed because the input is not positive-definite (the leading minor of order 6 is not positive-definite).' I tried to fix it at the code where the problem occurred, but the predicted results are not satisfactory.
Attachment is the original relevant code where the problem occurred and the code I used to fix it accordingly.
If you need more detailed information, I am ready to send it to you.
I wonder if you have also encountered this problem and how you solved it. Thank you for your guidance and answers.













At 2022-05-03 15:29:23, "Wessel" ***@***.***> wrote:

Hey @SGH-188,

Thanks for opening an issue!

The code should already be compatible with multidimensional inputs. For example, the Jura experiment uses two-dimensional inputs. I'm closing the issue for now, but if you encounter any issues, please feel free to reopen it or leave a comment here. :)

**Comment by wesselb** [comment]
Hey @SGH-188!

This typically happens when the covariance matrix of the data is ill conditioned. At the top of your script, could you try to run

```
import lab as B

B.epsilon = 1e-6 
```

`B.epsilon` determines the regularisation of the covariance matrices before inversion. `1e-6` is fairly high and should suffice; however, you could try setting it higher if the problem persists.

**Comment by SGH-188** [comment]
Dear wesselb:
Thank you for your guidance reply. I initially tried to run the changed code. After changing B.epsilon, the errors as last time disappeared. Next, I will further apply the code you provided. Thank you again for your advice.


Best wishes for you
Yours sincerely 
SGH










At 2022-07-28 01:07:32, "Wessel" ***@***.***> wrote:

Hey @SGH-188!

This typically happens when the covariance matrix of the data is ill conditioned. At the top of your script, could you try to run

import lab as B

B.epsilon = 1e-6 


B.epsilon determines the regularisation of the covariance matrices before inversion. 1e-6 is fairly high and should suffice; however, you could try setting it higher if the problem persists.
